# Generated by Django 3.2.5 on 2021-07-06 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('story_line', models.TextField(default='NOT AVAILABLE', max_length=1024)),
                ('img', models.ImageField(default='/images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
